// the default depo.json file
import { getRedirectUrl } from "@/utils/getRedirectUrl.ts";

export const DEFAULT_DEPO_JSON: Record<string, Record<string, any>> = {
  "module": {
    "name": Deno.cwd().split("/")?.slice(-1)[0] ?? "modulename",
    
  },
  "depo": {
    "version": "0.0.0",
    "generation": {
      "warning": "// Content below this comment is auto-generated by Depo",
    },
    //"ignore": []
  },
  "deno": {
    "std": {
      "version": "0.210.0"
    },
    "deps": {
      "location": "deps.ts"
    }
  },
  "esm": {
    "version": "v135",
  },
};

// DEPO_JSON is either the project's depo.json file or the default one
let DEPO_JSON: typeof DEFAULT_DEPO_JSON;
try {
  DEPO_JSON = JSON.parse(await Deno.readTextFile("./depo.json"));
} catch {
  DEPO_JSON = DEFAULT_DEPO_JSON;
}
export { DEPO_JSON };
