import { DEPO_JSON } from "../meta/depo.json.ts";
import { run } from "../utils/utils.ts";
import { DENO_JSON } from "../meta/deno.json.ts";
import { stableDenoStd, unstableDenoStd } from "../meta/deno.std.ts";

// add the flags to the esm.sh url
function buildQueryParameters(flags: Record<string, any>) {
  let query = "?";
  for (const key in flags) {
    const value = flags[key];
    if (value === true) {
      query += `${key}&`;
    } else if (typeof value === "string" && key !== "as") {
      query += `${key}=${value}&`;
    }
  }
  return query.slice(0, -1);
}

// get the redirect url to get the version
async function getRedirectUrl(url: string): Promise<string> {
  const response = await fetch(url, { redirect: "manual" });
  if (response.status === 301 || response.status === 302) {
    return response.headers.get("location") || "";
  }
  return url;
}

export async function install(
  source: string,
  pkg: string,
  flags: Record<string, any> | string,
) {
  //console.log("installing", source, pkg, flags);
  let stringFlags = "";
  if (typeof flags === "string") {
    stringFlags = flags;
    flags = {};
  }

  // use an alias if specified
  let aliasedPkg: string = flags.as ?? pkg;

  // only take before the @, ignoring an @ if it starts with it
  // like worst case scenario:
  // @babel/core@^5.0.0
  if (aliasedPkg.slice(1).includes("@")) {
    aliasedPkg = aliasedPkg.slice(0, aliasedPkg.slice(1).indexOf("@", 0) + 1);
  }

  // check if a standard module module is being installed
  if (unstableDenoStd.has(aliasedPkg) || stableDenoStd.has(aliasedPkg)) {
    DENO_JSON["imports"][aliasedPkg] =
      `https://deno.land/std@${DEPO_JSON.deno.std.version}/${aliasedPkg}/mod.ts` +
      buildQueryParameters(flags);
    Deno.writeTextFileSync("deno.json", JSON.stringify(DENO_JSON, null, 2));
  } else {
    switch (source) {
      case "node": {
        DENO_JSON["imports"][aliasedPkg] = await getRedirectUrl(
              `https://esm.sh/${DEPO_JSON.esm.version}/${pkg}`,
            ) +
            buildQueryParameters(flags) || stringFlags || "";
        break;
      }
      case "github": {
        aliasedPkg = aliasedPkg.split("/")[1];
        DENO_JSON["imports"][aliasedPkg] = `https://esm.sh/gh/${pkg}` +
            buildQueryParameters(flags) || stringFlags || "";
        break;
      }
      default: { // deno
        if (aliasedPkg.includes("/")) {
          aliasedPkg = aliasedPkg.slice(0, aliasedPkg.indexOf("/"));
        }
        DENO_JSON["imports"][aliasedPkg] = `https://deno.land/x/${pkg}` +
            buildQueryParameters(flags) || stringFlags || "";
        break;
      }
    }
    Deno.writeTextFileSync("deno.json", JSON.stringify(DENO_JSON, null, 2));
  }

  // generate deps.ts
  /*
  let DEPS_JSON = ["// This file is auto-generated by Depo", ""];
  let exports = [];

  for (const [key, value] of Object.entries(DENO_JSON["imports"])) {
    if (key === "deps") {
      continue;
    }
    const modifiedKey = key.replaceAll("/", "__").replaceAll("-", "_")
      .replaceAll("@", "");
    console.log(modifiedKey, value);
    DEPS_JSON.push(`import * as ${modifiedKey} from "${value}";`);
    exports.push(`${modifiedKey}`);
  }

  DEPS_JSON.push("");
  DEPS_JSON.push(`export { ${exports.join(", ")} };`);

  Deno.writeTextFileSync("src/deps.ts", DEPS_JSON.join("\n"));
  */
  // cache deps
  // run("deno", { args: ["cache", "src/deps.ts"] });
}
