// This file is auto-generated by Depo

import * as moment from "https://esm.sh/v135/moment";
import * as node_html_parser from "https://esm.sh/v135/node-html-parser";
import * as assert from "https://deno.land/std@0.210.0/assert/mod.ts";
import * as log from "https://deno.land/std@0.210.0/log/mod.ts";

export { moment, node_html_parser, assert, log };