# # currently does not do anything

# name: Build and Release

# on:
#   push:
#     branches:
#       - 'v[0-9]+.*' # This will match branches like v1.0, v2.3, etc.

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Setup Deno
#       uses: denoland/setup-deno@v1
#       with:
#         deno-version: v1.x

#     - name: Read VERSION
#       id: version
#       run: echo "::set-output name=VERSION::$(cat VERSION)"

#     - name: Build binary
#       run: deno compile --unstable --allow-read --allow-write --allow-net --allow-env --allow-run --output=./depo ./src/mod.ts

#     - name: Create Release
#       id: create_release
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: ${{ steps.version.outputs.VERSION }}
#         release_name: Release ${{ steps.version.outputs.VERSION }}
#         draft: false
#         prerelease: false

#     - name: Upload Release Asset
#       id: upload_release_asset
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_path: ./depo
#         asset_name: depo
#         asset_content_type: application/octet-stream